version: '3.9'

services:
  db:
    container_name: db_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: khoa190516
      POSTGRES_PASSWORD: Huynhthekhoa19052016
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - mynetwork

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: Huynhthekhoa19052016
    ports:
      - "5050:80"
    networks:
      - mynetwork
    depends_on:
      - db
  
  api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 5000:80
    depends_on:
      - db
    networks:
      - mynetwork

  web:
    build: ../khoaht3-eshop
    ports:
      - 3002:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mynetwork

volumes:
  pg_data:

networks:
  mynetwork:
    driver: bridge
